on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.56.0
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy, rustfmt
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo build
      - run: RUST_BACKTRACE=1 cargo test
      - run: cd examples && cargo run -- ../assets/test.mp3
